CREATE TABLE CONFIGURATION.FINALTABLE (
	"DOMAIN" VARCHAR(25),
	"SUBDOMAIN" VARCHAR(50),
	"KEY" VARCHAR(200),
	"VALUE" VARCHAR(8000),
	"LABEL" VARCHAR(64),
	"PRIORITY" INTEGER,
    "APPLICATION" VARCHAR(200),
    "UPDATETTM" TIMESTAMP,
    "UPDATEUSER" VARCHAR (25),
    "COREFLAG" SMALLINT
); 